version: "3"
services:
  angular-app:
    image: nadertarekcs/angular-service
    stdin_open: true
    ports: 
      - "80:80"
    networks:
      - mean-app
  api-server:
   environment:
      - MONGO_URI
      - NODE_ENV=production
    image: nadertarekcs/back-end-service
    ports:
      - "5000:8080"
    networks:
      - mean-app
networks:
  mean-app:
    driver: bridge
