swagger: '2.0'
info:
  description: This is a simple API
  version: 1.0.0
  title: Simple Inventory API
  contact:
    email: ramadan.ibrahem98@eng-st.cu.edu.eg

  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

# tags are used for organizing operations
tags:
# - name: admins
#   description: Secured Admin-only calls
- name: developers
  description: Operations available to regular developers
- name: users
  description: Operations available to regular users

paths:
  /api/v1/categories:
    get:
      tags:
      - developers
      - users
      summary: get all categories
      operationId: getAllCategories
      description: |
        Get all Categories of places to visit
      parameters:
      - in: query
        name: limit
        description: maximum number of records to return
        type: integer
        format: int32
        minimum: 1
        # maximum: 50
      responses:
        200:
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/CategoryItems'
        400:
          description: bad input parameter
definitions:
  CategoryItems:
    type: object
    required:
      - success
      - count
      - data
    properties:
      id:
        type: string
        example: 616bfd1b2458ec97206f4ba0
      name:
        type: string
        example: Theatre
      palces:
        type: array
        items:
          $ref: '#/definitions/Place'
  CategoryItem:
    type: object
    required:
      - id
      - name
      - places
    properties:
      id:
        type: string
        example: 616bfd1b2458ec97206f4ba0
      name:
        type: string
        example: Theatre
      palces:
        type: array
        items:
          $ref: '#/definitions/Place'
  Place:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: string
        example: 616bfd1b2458ec97206f4ba0
      name:
        type: string
        example: Cinema Metro

basePath: /api/v1
schemes:
  - http
  - https
